print('Programa que compara un nombre amb el nombre 10')
nombre=eval(input('Escriu un número : '))
print('El nombre',nombre,'és més gran o igual que 10?')
print(nombre>10)
print('El nombre',nombre,'és menor de 10?')
print(nombre<10)