print('Programa que analitza una paraula')
paraula = input('Escriu una paraula :')
print('La paraula ',paraula,' té ',len(paraula),'caràcters')
print('La primera lletra és',paraula[0])
print('La última lletra és',paraula[len(paraula)-1])
print('Les 2 primeres lletres són',paraula[:2])
print('Les 2 últimes lletres són')