print('Programa que fa la multiplicació de dos nombres')
n1=input('Escriu el primer nombre : ')
n2=input('Escriu el segon nombre : ')
multi=eval(n1)*eval(n2)
print('La multiplicació de', n1, 'i', n2, 'és ',multi)