print('Programa per realitzar càlculs')
num1=eval(input('Escriu el primer nombre :'))
num2=eval(input('Escriu el segon nombre :'))
print('Operacions amb', num1, 'i', num2)
print(num1,'+',num2,'=', num1+num2)
print(num1,'-',num2,'=', num1-num2)
print(num1,'x',num2,'=', num1*num2)
print(num1,'//',num2,'=', num1//num2)
